// <auto-generated />
using DogInfo.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DogInfo.Persistence.Migrations
{
    [DbContext(typeof(DogInfoDbContext))]
    [Migration("20241212145539_UpdateModel")]
    partial class UpdateModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DogInfo.Domain.Entities.Breed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FemaleWeightMax")
                        .HasColumnType("int");

                    b.Property<int>("FemaleWeightMin")
                        .HasColumnType("int");

                    b.Property<bool>("Hypoallergenic")
                        .HasColumnType("bit");

                    b.Property<int>("LifeSpanMax")
                        .HasColumnType("int");

                    b.Property<int>("LifeSpanMin")
                        .HasColumnType("int");

                    b.Property<int>("MaleWeightMax")
                        .HasColumnType("int");

                    b.Property<int>("MaleWeightMin")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Breeds");
                });
#pragma warning restore 612, 618
        }
    }
}
